apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartgenie-qa
resources:
  - namespace.yaml
  - ../../apps/base
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/environment: qa
patches:
  - path: agent-assistant-patch.yaml
  - path: agent-analytics-patch.yaml
