apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartgenie-prod
resources:
  - namespace.yaml
  - ../../base/sample-service
labels:
  - pairs:
      app.kubernetes.io/environment: prod
images:
  - name: smartgenie-sample
    newName: ghcr.io/ss12dev/smartgenie-sample
    newTag: 4429eaa7ac061aa66f7e403f0dd6fca1c8e93b4c
