apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sg-helm-charts
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/SS12dev/sg-helm-charts
  ref:
    branch: main
